-
  name: Add DNS server to resolv.conf
  hosts: localhost
  tasks: 
    -
      name: Add DNS server to resolv.conf
      lineinfile:
        path: /etc/resolv.conf
        line: 'nameserver 10.1.250.10'