- 
  name: Start services in order
  hosts: localhost
  tasks:
    -
      name: Start the database service
      service: name=postgres state=started
    -
      name: Start the httpd service
      service: name=httpd state=started
    -
      name: Start the nginx service
      service: 
        name: nginx
        state: started